<?php

namespace Tests\Feature\Http\Controllers\Api\Mobile;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Mobile\TracksController
 */
class TracksControllerTest extends TestCase
{
    /**
     * @test
     */
    public function latest_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('tracks/latest');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function popular_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('tracks/popular');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
