<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AccountController
 */
class AccountControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('account:settings', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_notifications_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('notifications');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_register_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('register');

        $response->assertRedirect(to(config('poniverse.urls')['register']));

        // TODO: perform additional assertions
    }

    // test cases...
}
