<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminController
 */
class AdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_announcements_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/announcements');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_classifier_queue_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/tracks/unclassified');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_genres_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/genres');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_show_songs_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/show-songs');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_tracks_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/tracks');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_users_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/users');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    // test cases...
}
