<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ArtistsController
 */
class ArtistsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_content_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{slug}/content');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_favourites_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{slug}/favourites');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('artists');

        $response->assertOk();
        $response->assertViewIs('artists.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_profile_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{slug}');

        $response->assertRedirect(action('ArtistsController@getProfile', [$newUser->slug]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_shortlink_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('users/{id}-{slug}');

        $response->assertRedirect(action('ArtistsController@getProfile', [$user->slug]));

        // TODO: perform additional assertions
    }

    // test cases...
}
