<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ContentController
 */
class ContentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_albums_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{slug}/account/albums/create');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_tracks_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('{slug}/account/tracks/edit/{id}');

        $response->assertOk();
        $response->assertViewIs('shared.null');

        // TODO: perform additional assertions
    }

    // test cases...
}
