<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ImagesController
 */
class ImagesControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_image_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $image = \App\Models\Image::factory()->create();
        $image = \App\Models\Image::factory()->create();
        $image = \App\Models\Image::factory()->create();

        $response = $this->get('i{id}/{type}.{extension}');

        $response->assertRedirect(to($redirect));

        // TODO: perform additional assertions
    }

    // test cases...
}
