<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PlaylistsController
 */
class PlaylistsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_download_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();
        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->get('p{id}/dl.{extension}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('playlists');

        $response->assertOk();
        $response->assertViewIs('playlists.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_playlist_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();
        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->get('playlist/{id}-{slug}');

        $response->assertRedirect(action('PlaylistsController@getPlaylist', [$id, $playlist->slug]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_shortlink_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $playlist = \App\Models\Playlist::factory()->create();

        $response = $this->get('p{id}');

        $response->assertRedirect(action('PlaylistsController@getPlaylist', [$id, $playlist->slug]));

        // TODO: perform additional assertions
    }

    // test cases...
}
