<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TracksController
 */
class TracksControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function get_download_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();
        $track = \App\Models\Track::factory()->create();

        $response = $this->get('t{id}/dl.{extension}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();
        $track = \App\Models\Track::factory()->create();

        $response = $this->get('tracks/{id}-{slug}/edit');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_embed_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();

        $response = $this->get('t{id}/embed');

        $response->assertOk();
        $response->assertViewIs('tracks.embed');
        $response->assertViewHas('track');
        $response->assertViewHas('user');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('tracks/popular');

        $response->assertOk();
        $response->assertViewIs('tracks.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_oembed_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('oembed');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_shortlink_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();

        $response = $this->get('t{id}');

        $response->assertRedirect(action('TracksController@getTrack', [$id, $track->slug]));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_stream_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();
        $track = \App\Models\Track::factory()->create();

        $response = $this->get('t{id}/stream.{extension}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_track_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $track = \App\Models\Track::factory()->create();
        $track = \App\Models\Track::factory()->create();

        $response = $this->get('tracks/{id}-{slug}');

        $response->assertRedirect(action('TracksController@getTrack', [$id, $track->slug]));

        // TODO: perform additional assertions
    }

    // test cases...
}
