<?php

namespace Tests\Feature\Http\Controllers\Api\Web;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\Web\TaxonomiesController
 */
class TaxonomiesControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_all_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('api/web/taxonomies/all');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
